server {
    listen 80;
    server_name {{DOMAIN}};
    root {{WEBROOT}};
    index index.html index.htm index.php;

    access_log /home/wwwlogs/{{DOMAIN}}.log main;
    error_log /home/wwwlogs/{{DOMAIN}}.error.log;

    # include rewrite/wordpress.conf;

    location ~ \.php$ {
        fastcgi_pass unix:/tmp/php-cgi.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }

    location ~ /\. {
        deny all;
    }
}
